name: "Setup Operator environment"
description: "Setup a operator environment"
author: "Adam Stokes"
inputs:
  provider:
    description: |
      Which Juju provider to use. Can be "lxd", "microk8s" or "microstack",
      or a cloud added via the credentials-yaml and clouds-yaml inputs.
    required: false
    default: "lxd"
  channel:
    description: "snap channel for the providers which are installed via snap"
    required: false
    default: ""
  credentials-yaml:
    description: "A base64-encoded credentials.yaml file to use."
    required: false
    default: ""
  clouds-yaml:
    description: "A base64-encoded clouds.yaml file to use."
    required: false
    default: ""
  bootstrap-options:
    description: "Additional options to pass to the bootstrap."
    required: false
    default: ""
  charm-channel:
    description: "snap channel for charm, installed via snap"
    required: false
    default: "latest/stable"
  charmcraft-channel:
    description: "snap channel for charmcraft, installed via snap"
    required: false
    default: "latest/stable"
  juju-channel:
    description: "snap channel for juju, installed via snap"
    required: false
    default: "latest/stable"
  juju-bundle-channel:
    description: "snap channel for juju bundle, installed via snap"
    required: false
    default: "latest/stable"
  lxd-channel:
    description: "snap channel for lxd regardless of provider, installed via snap"
    required: false
    default: "latest/stable"
  juju-crashdump-channel:
    description: "snap channel for juju-crashdump, installed via snap"
    required: false
    default: "latest/stable"
runs:
  using: "node12"
  main: "dist/bootstrap/index.js"
  post: "dist/cleanup/index.js"
branding:
  icon: "play"
  color: "blue"
