name: "Setup Operator environment"
description: "Setup a operator environment"
author: "Adam Dyess"
inputs:
  concierge-channel:
    description: |
      Channel of concierge to install
      https://snapcraft.io/concierge
    required: false
    default: "latest/stable"
  provider:
    description: |
      Which Juju provider to use. Can be "lxd", "microk8s" or "microstack",
      or a cloud added via the credentials-yaml and clouds-yaml inputs.
    required: false
    default: "lxd"
  channel:
    description: "snap channel for the providers which are installed via snap"
    required: false
    default: ""
  credentials-yaml:
    description: "A base64-encoded credentials.yaml file to use."
    required: false
    default: ""
  clouds-yaml:
    description: "A base64-encoded clouds.yaml file to use."
    required: false
    default: ""
  bootstrap-options:
    description: "Additional options to pass to the bootstrap excluding constraints."
    required: false
    default: ""
  bootstrap-constraints:
    description: "Additional options to pass as bootstrap constraints."
    required: false
    default: "cores=2 mem=4G"
  charm-channel:
    description: "snap channel for charm, installed via snap"
    required: false
    default: "latest/stable"
  charmcraft-channel:
    description: "snap channel for charmcraft, installed via snap"
    required: false
    default: "latest/stable"
  juju-channel:
    description: "snap channel for juju, installed via snap"
    required: false
    default: "3/stable"
  juju-bundle-channel:
    description: |-
      snap channel for juju bundle, installed via snap
      if unset, uses a stable revision
    required: false
    default: ""
  lxd-channel:
    description: |-
      snap channel for lxd, installed via snap

      Ignored if inputs.provider="lxd" and inputs.channel is non-empty
    required: false
    default: "latest/stable"
  juju-crashdump-channel:
    description: |-
      snap channel for juju-crashdump, installed via snap
      if unset, uses a stable revision
    required: false
    default: ""
  microk8s-group:
    description: "microk8s group name"
    required: false
    default: ""
  microk8s-addons:
    description: "microk8s addons to enable"
    required: false
    default: "storage dns rbac"
  tox-version:
    description: "Version of tox to install"
    required: false
    default: ""
  container-registry-url:
    description: "Container registry to use"
runs:
  using: node20
  main: ./dist/bootstrap/index.js
  post: ./dist/cleanup/index.js

branding:
  icon: "cloud"
  color: "blue"
