#!/bin/bash

set -e

unmatched_changes=false
dist_changes="$(git diff --cached --name-only dist)"
for src_filename in $(git diff --cached --name-only src); do
    dist_filename="${src_filename/src/dist}"
    dist_filename="${dist_filename/.ts/.js}"
    if [[ "$dist_changes" != *"$dist_filename"* ]]; then
        echo "Changes to $src_filename but not $dist_filename"
        unmatched_changes=true
    fi
done
if [[ "$unmatched_changes" == "true" ]]; then
    echo
    echo "Did you forget to run 'npm run build' or stage dist/*?"
    echo "(Use 'git commit --no-verify' to override.)"
    exit 1
fi
